server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to backend microservices
    location /api/users/ {
        proxy_pass http://user-service:8000/users/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/itineraries {
        proxy_pass http://itinerary-service:3000/itineraries;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
