name: Kubernetes Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  k8s-test:
    name: Test Kubernetes Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - name: Deploy to Kubernetes Cluster
        run: |
          kubectl apply -f k8s/travelgrid.yaml
          
          # Wait a few seconds for resources to register
          sleep 10
          
          # Check deployments
          kubectl get all -n travelgrid
          
          # Wait for the Pod to report its status, but we won't wait for the LoadBalancer since it's locally simulated.
          kubectl wait --for=condition=available --timeout=60s deployment/travelgrid-app -n travelgrid
